// Code generated by protoc-gen-go.
// source: goMicroservice/app/proto/app.proto
// DO NOT EDIT!

/*
Package app is a generated protocol buffer package.

It is generated from these files:
	goMicroservice/app/proto/app.proto

It has these top-level messages:
*/
package app

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import auth "goMicroservice/auth/proto"
import db "goMicroservice/db/proto"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for App service

type AppClient interface {
	GetTodoList(ctx context.Context, in *auth.AuthRequest, opts ...client.CallOption) (*db.DbResponse, error)
}

type appClient struct {
	c           client.Client
	serviceName string
}

func NewAppClient(serviceName string, c client.Client) AppClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "app"
	}
	return &appClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *appClient) GetTodoList(ctx context.Context, in *auth.AuthRequest, opts ...client.CallOption) (*db.DbResponse, error) {
	req := c.c.NewRequest(c.serviceName, "App.GetTodoList", in)
	out := new(db.DbResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for App service

type AppHandler interface {
	GetTodoList(context.Context, *auth.AuthRequest, *db.DbResponse) error
}

func RegisterAppHandler(s server.Server, hdlr AppHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&App{hdlr}, opts...))
}

type App struct {
	AppHandler
}

func (h *App) GetTodoList(ctx context.Context, in *auth.AuthRequest, out *db.DbResponse) error {
	return h.AppHandler.GetTodoList(ctx, in, out)
}

func init() { proto.RegisterFile("goMicroservice/app/proto/app.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 136 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x52, 0x4a, 0xcf, 0xf7, 0xcd,
	0x4c, 0x2e, 0xca, 0x2f, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0xd5, 0x4f, 0x2c, 0x28, 0xd0, 0x2f,
	0x28, 0xca, 0x2f, 0xc9, 0x07, 0xb1, 0xf4, 0xc0, 0x2c, 0x29, 0x15, 0x74, 0x35, 0xa5, 0x25, 0x19,
	0x30, 0x45, 0xa5, 0x25, 0x19, 0x50, 0x55, 0x0a, 0x68, 0xaa, 0x52, 0x92, 0xa0, 0x6a, 0x52, 0x92,
	0x20, 0x2a, 0x8c, 0x0c, 0xb9, 0x98, 0x1d, 0x0b, 0x0a, 0x84, 0xb4, 0xb8, 0xb8, 0xdd, 0x53, 0x4b,
	0x42, 0xf2, 0x53, 0xf2, 0x7d, 0x32, 0x8b, 0x4b, 0x84, 0x78, 0xf4, 0x1c, 0x4b, 0x4b, 0x32, 0x82,
	0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0xa4, 0xb8, 0xf5, 0x5c, 0x92, 0x82, 0x52, 0x8b, 0x0b, 0xf2,
	0xf3, 0x8a, 0x53, 0x95, 0x18, 0x92, 0xd8, 0xc0, 0x3a, 0x8d, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff,
	0xa8, 0x2f, 0x6c, 0x21, 0xa7, 0x00, 0x00, 0x00,
}
