// Code generated by protoc-gen-go.
// source: goMicroservice/db/proto/db.proto
// DO NOT EDIT!

/*
Package db is a generated protocol buffer package.

It is generated from these files:
	goMicroservice/db/proto/db.proto

It has these top-level messages:
	Todo
	DbResponse
*/
package db

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import auth "goMicroservice/auth/proto"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Todo struct {
	Task   string `protobuf:"bytes,1,opt,name=task" json:"task,omitempty"`
	Status string `protobuf:"bytes,2,opt,name=status" json:"status,omitempty"`
}

func (m *Todo) Reset()                    { *m = Todo{} }
func (m *Todo) String() string            { return proto.CompactTextString(m) }
func (*Todo) ProtoMessage()               {}
func (*Todo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type DbResponse struct {
	Username string  `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	TodoList []*Todo `protobuf:"bytes,2,rep,name=todoList" json:"todoList,omitempty"`
}

func (m *DbResponse) Reset()                    { *m = DbResponse{} }
func (m *DbResponse) String() string            { return proto.CompactTextString(m) }
func (*DbResponse) ProtoMessage()               {}
func (*DbResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *DbResponse) GetTodoList() []*Todo {
	if m != nil {
		return m.TodoList
	}
	return nil
}

func init() {
	proto.RegisterType((*Todo)(nil), "Todo")
	proto.RegisterType((*DbResponse)(nil), "DbResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for DB service

type DBClient interface {
	LoadTodoList(ctx context.Context, in *auth.AuthResponse, opts ...client.CallOption) (*DbResponse, error)
}

type dBClient struct {
	c           client.Client
	serviceName string
}

func NewDBClient(serviceName string, c client.Client) DBClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "db"
	}
	return &dBClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *dBClient) LoadTodoList(ctx context.Context, in *auth.AuthResponse, opts ...client.CallOption) (*DbResponse, error) {
	req := c.c.NewRequest(c.serviceName, "DB.LoadTodoList", in)
	out := new(DbResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for DB service

type DBHandler interface {
	LoadTodoList(context.Context, *auth.AuthResponse, *DbResponse) error
}

func RegisterDBHandler(s server.Server, hdlr DBHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&DB{hdlr}, opts...))
}

type DB struct {
	DBHandler
}

func (h *DB) LoadTodoList(ctx context.Context, in *auth.AuthResponse, out *DbResponse) error {
	return h.DBHandler.LoadTodoList(ctx, in, out)
}

func init() { proto.RegisterFile("goMicroservice/db/proto/db.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 202 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x5c, 0x8e, 0xc1, 0x4a, 0xc4, 0x30,
	0x10, 0x86, 0xdd, 0xba, 0x2e, 0xeb, 0xac, 0x5e, 0x72, 0x90, 0xd2, 0x53, 0x2d, 0x1e, 0xf6, 0x20,
	0x29, 0xc4, 0x27, 0x50, 0x7a, 0xb3, 0x5e, 0x4a, 0x5f, 0x20, 0x69, 0x82, 0x2d, 0x62, 0xa7, 0x64,
	0x26, 0x3e, 0xbf, 0x34, 0xc6, 0x0a, 0xde, 0xfe, 0xff, 0xe7, 0x1b, 0xbe, 0x81, 0xf2, 0x1d, 0xdf,
	0xa6, 0xc1, 0x23, 0x39, 0xff, 0x35, 0x0d, 0xae, 0xb6, 0xa6, 0x5e, 0x3c, 0x32, 0xd6, 0xd6, 0xc8,
	0x18, 0x8a, 0x87, 0x7f, 0x84, 0x0e, 0x3c, 0x26, 0x66, 0x8d, 0x3f, 0x54, 0xa5, 0x60, 0xdf, 0xa3,
	0x45, 0x21, 0x60, 0xcf, 0x9a, 0x3e, 0xf2, 0x5d, 0xb9, 0x3b, 0x5f, 0x77, 0x31, 0x8b, 0x3b, 0x38,
	0x10, 0x6b, 0x0e, 0x94, 0x67, 0x71, 0x4d, 0xad, 0x7a, 0x05, 0x68, 0x4c, 0xe7, 0x68, 0xc1, 0x99,
	0x9c, 0x28, 0xe0, 0x18, 0xc8, 0xf9, 0x59, 0x7f, 0xba, 0x74, 0xbd, 0x75, 0x71, 0x0f, 0x47, 0x46,
	0x8b, 0xed, 0x44, 0x9c, 0x67, 0xe5, 0xe5, 0xf9, 0xa4, 0xae, 0xe4, 0xaa, 0xeb, 0xb6, 0x59, 0x29,
	0xc8, 0x9a, 0x17, 0xf1, 0x08, 0x37, 0x2d, 0x6a, 0xdb, 0xa7, 0x55, 0xdc, 0xca, 0xe7, 0xc0, 0xe3,
	0xaf, 0xa3, 0x38, 0xc9, 0x3f, 0x61, 0x75, 0x61, 0x0e, 0xf1, 0xf7, 0xa7, 0xef, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x7f, 0xbc, 0xca, 0xe3, 0x05, 0x01, 0x00, 0x00,
}
